#!/usr/bin/env python3
"""Generate the measured table's four ArUco models as native Gazebo visuals.

Run with ``.venv/bin/python scripts/generate_gazebo_aruco.py``. OpenCV is only
needed for generation; Gazebo loads the committed models without it or textures.
Use ``--check`` to verify the committed outputs without modifying them.

The IDs and 50 mm black-square size come from
``training/calibration/workspace_markers.yaml``. The old moveo_R5A textures use
the same DICT_4X4_50 patterns, which match DICT_4X4_1000 for these IDs. A 52 mm
white backing fits the measured table margins. Local +X points image-right,
+Y image-up, and +Z out of the printed surface; world poses set the marker yaw.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2


MARKER_IDS = (19, 23, 25, 26)
BLACK_SIZE_M = 0.050
BACKING_SIZE_M = 0.052
GRID_SIZE = 6  # 4 payload cells plus one black border cell on each side.
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "mycobot_description/models"


def visual(name: str, x: float, y: float, z: float,
           width: float, height: float, depth: float, white: bool) -> str:
    color = "1 1 1 1" if white else "0 0 0 1"
    return f'''      <visual name="{name}">
        <pose>{x:.12f} {y:.12f} {z:.12f} 0 0 0</pose>
        <cast_shadows>false</cast_shadows>
        <geometry>
          <box><size>{width:.12f} {height:.12f} {depth:.12f}</size></box>
        </geometry>
        <material>
          <ambient>{color}</ambient>
          <diffuse>{color}</diffuse>
          <specular>0 0 0 1</specular>
        </material>
      </visual>
'''


def model_sdf(marker_id: int) -> str:
    dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
    pixels = cv2.aruco.generateImageMarker(dictionary, marker_id, GRID_SIZE)
    visuals = [
        visual("white_backing", 0, 0, 0.00005,
               BACKING_SIZE_M, BACKING_SIZE_M, 0.00010, True),
        visual("black_square", 0, 0, 0.00011,
               BLACK_SIZE_M, BLACK_SIZE_M, 0.00002, False),
    ]
    cell_size = BLACK_SIZE_M / GRID_SIZE
    for row in range(1, GRID_SIZE - 1):
        for col in range(1, GRID_SIZE - 1):
            if pixels[row, col] != 0:
                x = (col + 0.5) * cell_size - BLACK_SIZE_M / 2
                y = BLACK_SIZE_M / 2 - (row + 0.5) * cell_size
                visuals.append(visual(f"white_cell_{row}_{col}", x, y, 0.000125,
                                      cell_size, cell_size, 0.00001, True))
    return f'''<?xml version="1.0"?>
<!-- Generated by scripts/generate_gazebo_aruco.py; regenerate instead of editing.
     DICT_4X4_50 ID {marker_id}, also compatible with DICT_4X4_1000.
     Measured black square: 50 mm. White backing: 52 mm.
     Local +X = image right, +Y = image up, +Z = printed face normal.
     Visuals only: these paper markers add no collision surface. -->
<sdf version="1.9">
  <model name="aruco_{marker_id}">
    <static>true</static>
    <link name="marker">
{''.join(visuals)}    </link>
  </model>
</sdf>
'''


def model_config(marker_id: int) -> str:
    return f'''<?xml version="1.0"?>
<!-- Generated by scripts/generate_gazebo_aruco.py. -->
<model>
  <name>aruco_{marker_id}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>ArUco DICT_4X4_50 ID {marker_id}: 50 mm black square on a 52 mm white backing.</description>
</model>
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
                        help="Gazebo models directory (default: mycobot_description/models)")
    parser.add_argument("--check", action="store_true",
                        help="check generated files match without writing")
    args = parser.parse_args()
    mismatches = []
    for marker_id in MARKER_IDS:
        model_dir = args.output_dir / f"aruco_{marker_id}"
        for filename, content in (("model.sdf", model_sdf(marker_id)),
                                  ("model.config", model_config(marker_id))):
            path = model_dir / filename
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    mismatches.append(str(path))
            else:
                model_dir.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    if mismatches:
        print("Missing or outdated generated files:\n" + "\n".join(mismatches))
        return 1
    print(f"{'Checked' if args.check else 'Generated'} {len(MARKER_IDS)} ArUco models in {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
